import Head from 'next/head'

export default function Home() {
  return (
    <>
    <Head>
      <title>Shailesh Gehlot</title>
      <meta name="description" content='generated by create react app'/>
    </Head>
    <main>
      Hello
    </main>
    </>
  )
}
